diff -u -r1.4 Makefile
--- Makefile	30 Mar 2004 18:55:26 -0000	1.4
+++ Makefile	11 Aug 2005 08:07:37 -0000
@@ -6,7 +6,7 @@
 
 CC=     gcc
 
-CFLAGS= -Wall -O3 -DHAVE_MEMCPY
+CFLAGS+= -Wall -DHAVE_MEMCPY
 
 ifneq ($(OSTYPE),beos)
 INSTALL_PATH= /usr/local/bin
