#!/bin/sh
bld=(
	otf-cantarell-ib
	otf-cantoraone-ib
	otf-oswald-ib
	otf-quintessential-ib
	otf-tex-gyre-ib
	t1-urw-fonts-ib
	ttf-caladea-ib
	ttf-carlito-ib
	1_droid-ib
	ttf-gelasio-ib
	ttf-liberastika-ib
	ttf-merriweather-ib
	ttf-merriweather-sans-ib
	1_noto-family-ib
	1_noto-family-ib
	ttf-opensans-ib
	1_signika-family-ib
	ttf-ubuntu-font-family-ib
	ttf-ddc-uchen-ib
	ttf-faruma-ib
	ttf-lohit-odia-ib
	ttf-lohit-punjabi-ib
)
pkg=(
	otf-cantarell-ib
	otf-cantoraone-ib
	otf-oswald-ib
	otf-quintessential-ib
	otf-tex-gyre-ib
	t1-urw-fonts-ib
	ttf-caladea-ib
	ttf-carlito-ib
	ttf-droid-ib
	ttf-gelasio-ib
	ttf-liberastika-ib
	ttf-merriweather-ib
	ttf-merriweather-sans-ib
	ttf-noto-sans-multilang-ib
	ttf-noto-serif-multilang-ib
	ttf-opensans-ib
	ttf-signika-family-ib
	ttf-ubuntu-font-family-ib
	ttf-ddc-uchen-ib
	ttf-faruma-ib
	ttf-lohit-odia-ib
	ttf-lohit-punjabi-ib
)
echo 'SRC_URI=('
for x in ${!pkg[@]}; do
    y="https://raw.githubusercontent.com/bohoomil/fontconfig-ultimate/pkgbuild/${bld[${x}]}/PKGBUILD"
    _v=$(curl -s "${y}"|awk -F= '/pkg[vr]e[rl]=/ {print $2}'|tr '\n' '-')
    echo -e "\t${pkg[${x}]}-${_v%-}"
done
echo ')'
