Index: tools/Makefile
===================================================================
--- tools/Makefile	(revision 8324)
+++ tools/Makefile	(working copy)
@@ -1,29 +1,26 @@
 CC = gcc
 RM = rm -rf
 
-CFLAGS = -g -O0 -Wall -I.. -DTYPE=uint16_t
-LFLAGS = -g
+CFLAGS += -Wall -I.. -DTYPE=uint16_t
 
 TARGETS = pnmdiff yuv2ppm deinterlace
 
-OBJS = $(TARGETS:=.o) ../pnm.o
-SRCS = $(OBJS:.o=.c)
 
+%.o: %.c
+	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ -c $<
 
+
 all: $(OBJS) $(TARGETS)
 
 pnmdiff: pnmdiff.o ../pnm.o
-	$(CC) $(LFLAGS) pnmdiff.o ../pnm.o -o $@
+	$(CC) $(LDFLAGS) pnmdiff.o ../pnm.o -o $@
 
 yuv2ppm: yuv2ppm.o ../pnm.o
-	$(CC) $(LFLAGS) yuv2ppm.o ../pnm.o -o $@
+	$(CC) $(LDFLAGS) yuv2ppm.o ../pnm.o -o $@
 
 deinterlace: deinterlace.o ../pnm.o
-	$(CC) $(LFLAGS) deinterlace.o ../pnm.o -o $@
+	$(CC) $(LDFLAGS) deinterlace.o ../pnm.o -o $@
 
-.c.o: .depend
-	$(CC) $(CFLAGS) -c $< -o $@
-
 clean:
 	$(RM) $(OBJS) $(TARGETS) gmon.out core .depend .depend.bak
 
Index: Makefile
===================================================================
--- Makefile	(revision 8324)
+++ Makefile	(working copy)
@@ -1,8 +1,3 @@
-CC = gcc
-RM = rm -rf
-
-CFLAGS = -g -O0 -Wall -I../ogg/ogg/include
-
 # use 16 bit signed integers as wavelet coefficients
 CFLAGS+= -DTYPE=int16_t
 
@@ -22,53 +17,42 @@
 #CFLAGS+= -DDBG_OGG
 
 # disable assertions
-#CFLAGS+= -DNDEBUG
+CFLAGS+= -DNDEBUG
 
-LFLAGS = -g -lefence -logg -L../ogg/ogg/src/.libs
+LIBS = -L. -ltarkin -L/usr/lib -logg
 
-OBJS = mem.o pnm.o wavelet.o wavelet_xform.o wavelet_coeff.o \
-	yuv.o tarkin.o info.o
+TARGET=libtarkin.a
 
-TEST_TARGETS = _test_bitcoder _test_rle
+%.o: %.c
+	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ -c $<
 
-SRCS = $(OBJS:.o=.c)
-TEST_OBJS = $(TEST_TARGETS:=.o)
-TEST_SRCS = $(TEST_OBJS:.o=.c)
+SRCS= \
+	info.c \
+	mem.c \
+	pnm.c \
+	tarkin.c \
+	wavelet.c \
+	wavelet_coeff.c \
+	wavelet_xform.c \
+	yuv.c
 
+OBJS=$(SRCS:.c=.o)
 
-all: tarkin_enc tarkin_dec
+all: $(TARGET) tarkin_enc tarkin_dec tarkin_sdl_player
 
-tarkin_enc: $(OBJS) tarkin_enc.o
-	$(CC) $(LFLAGS) $(OBJS) tarkin_enc.o -o $@
+$(TARGET): $(OBJS)
+	$(AR) $(ARFLAGS) $@ $(OBJS)
+	ranlib $@
 
-tarkin_dec: $(OBJS) tarkin_dec.o
-	$(CC) $(LFLAGS) $(OBJS) tarkin_dec.o -o $@
+tarkin_enc: $(TARGET) tarkin_enc.o
+	$(CC) $(LDFLAGS) tarkin_enc.o -o $@ $(LIBS)
 
-tarkin_sdl_player: $(OBJS) tarkin_sdl_player.o
-	$(CC) $(LFLAGS) `sdl-config --libs` $(OBJS) tarkin_sdl_player.o -o $@
+tarkin_dec: $(TARGET) tarkin_dec.o
+	$(CC) $(LDFLAGS) tarkin_dec.o -o $@ $(LIBS)
 
+tarkin_sdl_player: $(TARGET) tarkin_sdl_player.o
+	$(CC) $(LDFLAGS) `sdl-config --libs` tarkin_sdl_player.o -o $@ $(LIBS)
+
 tarkin_sdl_player.o: tarkin_sdl_player.c
 	$(CC) $(CFLAGS) `sdl-config --cflags` -c $< -o $@
 
-.c.o: .depend
-	$(CC) $(CFLAGS) -c $<
-
-clean:
-	$(RM) $(OBJS) $(TARGET) gmon.out core .depend .depend.bak rle.histogram
-	$(RM) $(TEST_TARGETS) $(TEST_OBJS)
-	$(RM) tarkin_enc tarkin_dec tarkin_enc.o tarkin_dec.o
-	$(RM) tarkin_sdl_player tarkin_sdl_player.o
-	$(RM) stream.ogg
-	$(RM) *.ppm *.pgm
-
-test: .depend $(TEST_TARGETS)
-	./_test_bitcoder
-	./_test_rle
-
-.depend: $(SRCS) $(TEST_SRCS)
-	$(RM) .depend
-	touch .depend
-	sh tools/makedepend.sh -f.depend -- $(CFLAGS) -- $(SRCS) $(TEST_SRCS) tarkin_enc.c tarkin_dec.c
-
--include .depend
-
