Index: Makefile
===================================================================
--- Makefile	(revision 2575)
+++ Makefile	(working copy)
@@ -3,11 +3,13 @@
 PROGRAMS = exfalso quodlibet
 SUBDIRS = trayicon mmkeys po
 EXTENSIONS = _trayicon.so _mmkeys.so
-PREFIX ?= /usr/local
+PREFIX ?= /usr
 TO = share/quodlibet
 TODEP = lib/quodlibet
 
-all:
+all: check extensions po-data
+
+check:
 	@/bin/echo -n "Checking for Python... "
 	@which python || ( echo "Not found." && /bin/false )
 	@./check.py
